---
stages:
  - name: Build Stage
    inputs:
      - type: git
        branch: master
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: Deploy Stage
    inputs:
      - type: job
        stage: Build Stage
        job: Build
    triggers:
      - type: stage
    jobs:
      - name: Deploy to dev
        type: deployer
        script: |-
            #!/bin/bash
            cf create-service iotf-service iotf-service-free simulate-iot-iotf-service
            cf create-service cloudantNoSQLDB Lite simulate-iot-cloudantNoSQLDB
            cf create-service AvailabilityMonitoring Lite availability-monitoring-auto
            cf push ${CF_APP} --no-start
            cf bind-service ${CF_APP} simulate-iot-iotf-service
            cf bind-service ${CF_APP} simulate-iot-cloudantNoSQLDB
            cf bind-service ${CF_APP} availability-monitoring-auto
            cf restage ${CF_APP}
            cf start ${CF_APP}
        target:
          organization: ${CF_ORGANIZATION}
          space: ${CF_SPACE}
          url: ${CF_TARGET_URL}
          application: ${CF_APP}
